# This workflow will install dependencies, build, test, 
# and deploy only after admin approval.

name: Node.js CI/CD with Approval

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    needs: build   # 👈 Run only if build job succeeds
    runs-on: ubuntu-latest
    environment: production   # 👈 This enables approval gate
    steps:
      - name: Deploy Application
        run: echo "🚀 Deploying Node.js app to production..."
